### ISSUE TITLE
PIP repo is unaccessible

### ISSUE THREAD

**Issue by Yumash** [futurice/futurice-ldap-user-manager#25]
Subj

telnet pypi.fum.futurice.com 80
Trying 212.68.22.56...
telnet: Unable to connect to remote host: Connection refused

and https one is not a PIP repo.

django-history and others are undownloadable.

**Comment by ojarva** [comment]
Ping @mixman , is this still an issue?

**Comment by mixman** [comment]
With the recent Django 1.7 updates this was also fixed.
