### ISSUE TITLE
Audit log seems to be broken

### ISSUE THREAD

**Issue by harriha** [futurice/futurice-ldap-user-manager#57]
Person page -> 'Audit log' -> `https://fum.futurice.com/fum/history/by/ct/9/id/<userid>` === empty page apart from text `root / django-history: for users (#<userid>) <username>`

Assuming I should be able to see at least my own audit log - if not and this is about permissions, hiding/disabling the button might be :+1:.

**Comment by mixman** [comment]
Seems audit log was off. Turned it on.
